version: '{branch}.{build}'
environment:
  matrix:
    - PYTHON: "2.7"
      PYTHON_INSTALL: "2.7.14"
      VLC_INSTALL: "3.0.1"
      PIPENV_INSTALL: "9.0.3"
      should_deploy: yes
      #APPVEYOR_RDP_PASSWORD: Pou3t$
  GITHUB_TOKEN:
      secure: 3DxNrTsx301Sf5zVRJuKmup+SClBnsaXXvM16rA0JYPBljBvjid4kDl+18NfjPro
  APPVEYOR_API_TOKEN:
      secure: kkr9LewGDRWYZSggRa2+/39A8sPEJuRVVYZhecuuNDg=

platform:
  - x86
  - x64

init:
  # Taken from scikit-ci-addons/cancel-queued-build.ps1 to cancel the
  # queued builds that match latest/latest-tmp when using rolling releases
  # for the latest tag, as this tag is generated automatically after a
  # success build of the master branch, and artifacts will be uploaded
  # automatically too.
  - ps: |
      (Invoke-RestMethod https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=20).builds | Where-Object {$_.status -eq "queued" -and ( $_.tag -match '^latest(-tmp)?$' ) } | %{ $_.version } | %{
          $msg = "Found build version $_"
          Write-Host "  $msg"
          $url = "https://ci.appveyor.com/api/builds/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/$_"
          Invoke-RestMethod $url -Method Delete -Headers @{"Authorization" = "Bearer $env:APPVEYOR_API_TOKEN"};
          Write-Host "  $msg - cancelled"
      }
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ps: |
      if ($env:APPVEYOR_RDP_PASSWORD) {
        if ($env:PLATFORM -eq 'x64') {
            throw "Skipping one platform in debug mode"
        }
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

on_finish:
  - ps: |
      if ($env:APPVEYOR_RDP_PASSWORD) {
        $blockRdp = $true;
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

install:
  # Set the home for the Python version
  - set "PYTHON_HOME=C:\\Python%PYTHON:.=%"
  - if [%PLATFORM%]==[x64] set "PYTHON_HOME=%PYTHON_HOME%-x64"

  # Fix for x64 msvc9compiler.py
  - if [%PLATFORM%]==[x64] (
        if not exist "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat" (
            echo CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat" &
            echo Setting vcvars64.bat (fix for msvc9compiler.py^^^)
        ) else (
            echo vcvars64.bat already exists.
        )
    )

  # Print environment information
  - "echo Environment: Python %PYTHON% / Platform %PLATFORM% / %PYTHON_HOME%"

  # Install and configure Python in the path to use the needed version
  - if not exist "%PYTHON_HOME%" ( set "NEEDINSTALL=True" ) else ( set "NEEDINSTALL=False" )
  - "echo Does Python %PYTHON% (%PLATFORM%) need to be installed? %NEEDINSTALL%"
  - if [%NEEDINSTALL%]==[True] (
        if [%PLATFORM%]==[x64] (
            set "PYTHON_DL=python-%PYTHON_INSTALL%.amd64.msi"
        ) else (
            set "PYTHON_DL=python-%PYTHON_INSTALL%.msi"
        )
    )
  - if [%NEEDINSTALL%]==[True] (
        echo Downloading https://www.python.org/ftp/python/%PYTHON_INSTALL%/%PYTHON_DL% &
        appveyor DownloadFile https://www.python.org/ftp/python/%PYTHON_INSTALL%/%PYTHON_DL% &
        echo Installing %PYTHON_DL% in %PYTHON_HOME% &
        msiexec /i %PYTHON_DL% /qn TARGETDIR=%PYTHON_HOME%
    )
  - set "PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print('Architecture: {0}bit'.format(struct.calcsize('P') * 8))\""

  # Install pip
  - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - "python get-pip.py"
  - "pip --version"

  # Install dependencies
  - "pip install pipenv==%PIPENV_INSTALL%"
  - "pipenv --version"
  - "pipenv install --dev"

  # If the build should lead to a deployment, check that the tag is valid,
  # else, check what the current version will be
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          pipenv run "${env:APPVEYOR_BUILD_FOLDER}\version.py" 'check-tag' '--tag' "${env:APPVEYOR_REPO_TAG_NAME}"
          Invoke-Expression "$(pipenv run "${env:APPVEYOR_BUILD_FOLDER}\version.py" 'environment' '--version' "${env:APPVEYOR_REPO_TAG_NAME}")"
      } else {
          Invoke-Expression "$(pipenv run "${env:APPVEYOR_BUILD_FOLDER}\version.py" 'environment')"
      }
      printenv | grep '^TRAKT_VERSION' | sort
  # Set the binary name
  - ps: |
      $env:TRAKT_HELPER_BIN = "TraktForVLC_${env:TRAKT_VERSION}_windows_${env:PLATFORM}.exe"

  # Install VLC
  - if [%PLATFORM%]==[x64] (
        set "VLC_PLATFORM=win64"
    ) else (
        set "VLC_PLATFORM=win32"
    )
  - set "VLC_INST_EXE=vlc-%VLC_INSTALL%-%VLC_PLATFORM%.exe"
  - set "VLC_DL=http://download.videolan.org/pub/videolan/vlc/%VLC_INSTALL%/%VLC_PLATFORM%/%VLC_INST_EXE%"
  - echo Downloading %VLC_DL% &
    appveyor DownloadFile %VLC_DL%
  - echo Installing %VLC_INST_EXE% &
    "%APPVEYOR_BUILD_FOLDER%\\%VLC_INST_EXE%" /L=1033 /S /NCRC
  # Check VLC version information once installed
  - ps: |
      if (${env:PLATFORM} -eq "x64" -OR ${env:ProgramFiles(x86)} -eq $null) {
          $env:VLCPATH = "${env:ProgramFiles}"
      } else {
          $env:VLCPATH = "${env:ProgramFiles(x86)}"
      }
      $env:VLCPATH = "${env:VLCPATH}\VideoLAN\VLC"
      $env:VLCEXE = "${env:VLCPATH}\vlc.exe"
      $vlcVersion = Start-Process "${env:VLCEXE}" '--version' -PassThru
      $wshell = New-Object -ComObject wscript.shell
      $wshell.AppActivate('VLC media player')
      Start-Sleep -s 1
      $wshell.SendKeys('~')
      Start-Sleep -s 1
      Get-Content "vlc-help.txt"
  # We need to run VLC once, or next time we'll try to call it, we'll block on
  # it (it opens a window on first install on Windows...)
  - ps: |
      $vlc = Start-Process "${env:VLCEXE}" -PassThru
      $wshell = New-Object -ComObject wscript.shell
      $wshell.AppActivate('VLC media player')
      Start-Sleep -s 1
      $wshell.SendKeys('~')
      Start-Sleep -s 1
      Stop-Process $vlc

build_script:
  # Set the version in the Python and LUA scripts
  - "pipenv run \"%APPVEYOR_BUILD_FOLDER%\\version.py\" set --version=%TRAKT_VERSION%"
  # Compile the Lua scripts
  - ps: |
      & "${env:VLCEXE}" -I luaintf --lua-intf luac --lua-config "luac={input='trakt.lua',output='trakt.luac'}"
  # Then prepare the exe file
  - "pipenv run pyinstaller --onedir --onefile --name=%TRAKT_HELPER_BIN% --add-data=trakt.luac;. --console trakt_helper.py"
  # Test the exe file by first checking if the --version command returns properly
  - "\"%APPVEYOR_BUILD_FOLDER%\\dist\\%TRAKT_HELPER_BIN%\" --version"
  # Then print the help message
  - "\"%APPVEYOR_BUILD_FOLDER%\\dist\\%TRAKT_HELPER_BIN%\" --help"

test_script:
  # Prepare the variables to know where to check for the installation 
  - ps: |
      $env:CONFIG = "${env:APPDATA}\vlc"
      $env:LUA_USER = "${env:CONFIG}\lua"
      $env:LUA_SYSTEM = "${env:VLCPATH}\lua"
  
  ############################################################################
  # TEST INSTALLATION LOCALLY
  ############################################################################
  # Install with default parameters
  - "\"%APPVEYOR_BUILD_FOLDER%\\dist\\%TRAKT_HELPER_BIN%\" --debug install --yes"
  # Then we need to check if everything was installed as we would expect
  - ps: |
      ls "${env:LUA_USER}\trakt_helper.exe"
      ls "${env:LUA_USER}\intf\trakt.luac"
  # Run VLC through the helper to save the output, and kill it
  # after a few seconds
  - ps: |
      $vlc = Start-Process "${env:APPVEYOR_BUILD_FOLDER}\dist\${env:TRAKT_HELPER_BIN}" 'runvlc' -PassThru -RedirectStandardOutput 'vlc-output.log'
      Start-Sleep -s 5
      TASKKILL /IM 'vlc.exe'
  # Print VLC's output during that run
  - ps: |
      While ((Get-Content "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log") -eq $null) {
          echo "VLC output file empty, waiting 5 more seconds"
          Start-Sleep -s 5
      }
      ls "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log"
      Get-Content "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log"
  # Perform checks of execution using the log of that run
  - ps: |
      $matches = Select-String -Path "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log" -Pattern '\[trakt\] lua interface: helper: (.*)$'
      if ($matches.Count -eq 0) {
          Throw "The line declaring the helper was not found."
      } elseif ($matches.Matches.Groups[1].Value -ne "${env:LUA_USER}\trakt_helper.exe") {
          Throw "The helper found is located at $($matches.Matches.Groups[1].Value) instead of ${env:LUA_USER}\trakt_helper.exe"
      } else {
          echo "The helper was correctly found: $($matches.Matches.Groups[1].Value)"
      }
      $matches = Select-String -Path "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log" -Pattern '^TraktForVLC is not setup'
      if ($matches.Count -eq 0) {
          Throw "TraktForVLC was not requesting for Trakt.tv access :("
      } else {
          echo "TraktForVLC was requesting for Trakt.tv access :)"
      }
      $matches = Select-String -Path "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log" -Pattern '^TraktForVLC setup failed'
      if ($matches.Count -ne 0) {
          Throw "TraktForVLC failed (setup fail) before we stopped VLC :("
      } else {
          echo "TraktForVLC did not fail (setup fail) before we stopped VLC :)"
      }
  # Then uninstall
  - "\"%LUA_USER%\\trakt_helper.exe\" --debug uninstall --yes"
  # And check that the files are not there
  - ps: |
      $files = "${env:LUA_USER}\trakt_helper.exe","${env:LUA_USER}\intf\trakt.luac"
      $not_deleted = $false
      ForEach ($f in $files) {
          if (Test-Path "$f") {
              Write-Error "File $f exists but should have been deleted" -Category ResourceExists
              $not_deleted = $true
          } else {
              echo "File $f has been deleted properly"
          }
      }
      if ($not_deleted) {
          Throw "Some files have not been cleaned-up during uninstall"
      }

  ############################################################################
  # TEST INSTALLATION SYSTEM-WIDE
  ############################################################################
  # Install with default parameters
  - "\"%APPVEYOR_BUILD_FOLDER%\\dist\\%TRAKT_HELPER_BIN%\" --debug install --yes --system"
  # Then we need to check if everything was installed as we would expect
  - ps: |
      ls "${env:LUA_SYSTEM}\trakt_helper.exe"
      ls "${env:LUA_SYSTEM}\intf\trakt.luac"
  # Run VLC through the helper to save the output, and kill it
  # after a few seconds
  - ps: |
      $vlc = Start-Process "${env:APPVEYOR_BUILD_FOLDER}\dist\${env:TRAKT_HELPER_BIN}" 'runvlc' -PassThru -RedirectStandardOutput "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log"
      Start-Sleep -s 5
      TASKKILL /IM 'vlc.exe'
  # Print VLC's output during that run
  - ps: |
      While ((Get-Content "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log") -eq $null) {
          echo "VLC output file empty, waiting 5 more seconds"
          Start-Sleep -s 5
      }
      ls "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log"
      Get-Content "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log"
  # Perform checks of execution using the log of that run
  - ps: |
      $matches = Select-String -Path "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log" -Pattern '\[trakt\] lua interface: helper: (.*)$'
      if ($matches.Count -eq 0) {
          Throw "The line declaring the helper was not found."
      } elseif ($matches.Matches.Groups[1].Value -ne "${env:LUA_SYSTEM}\trakt_helper.exe") {
          Throw "The helper found is located at $($matches.Matches.Groups[1].Value) instead of ${env:LUA_SYSTEM}\trakt_helper.exe"
      } else {
          echo "The helper was correctly found: $($matches.Matches.Groups[1].Value)"
      }
      $matches = Select-String -Path "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log" -Pattern '^TraktForVLC is not setup'
      if ($matches.Count -eq 0) {
          Throw "TraktForVLC was not requesting for Trakt.tv access :("
      } else {
          echo "TraktForVLC was requesting for Trakt.tv access :)"
      }
      $matches = Select-String -Path "${env:APPVEYOR_BUILD_FOLDER}\vlc-output.log" -Pattern '^TraktForVLC setup failed'
      if ($matches.Count -ne 0) {
          Throw "TraktForVLC failed (setup fail) before we stopped VLC :("
      } else {
          echo "TraktForVLC did not fail (setup fail) before we stopped VLC :)"
      }
  # Then uninstall
  - "\"%LUA_SYSTEM%\\trakt_helper.exe\" --debug uninstall --yes --system"
  # And check that the files are not there
  - ps: |
      $files = "${env:LUA_SYSTEM}\trakt_helper.exe","${env:LUA_SYSTEM}\intf\trakt.luac"
      $not_deleted = $false
      ForEach ($f in $files) {
          if (Test-Path "$f") {
              Write-Error "File $f exists but should have been deleted" -Category ResourceExists
              $not_deleted = $true
          } else {
              echo "File $f has been deleted properly"
          }
      }
      if ($not_deleted) {
          Throw "Some files have not been cleaned-up during uninstall"
      }

artifacts:
  - path: 'dist\$(TRAKT_HELPER_BIN)'
    name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_BRANCH)-$(PLATFORM)

before_deploy:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          $env:RELEASE_DRAFT = $false;
          $env:RELEASE_PRE = $env:TRAKT_VERSION_PRE_TYPE -ne $null;
      } else {
          $env:TRAKT_VERSION_NAME = "$env:APPVEYOR_REPO_BRANCH-branch";
          $env:RELEASE_PRE = $false;
          $env:RELEASE_DRAFT = $true;
          $env:TRAKT_VERSION_DESCRIPTION = "Draft of release for branch $env:APPVEYOR_REPO_BRANCH. $env:TRAKT_VERSION_DESCRIPTION";
      }
  - ps: 'echo "RELEASE NAME: $env:TRAKT_VERSION_NAME"'
  - ps: 'echo "RELEASE DESCRIPTION: $env:TRAKT_VERSION_DESCRIPTION"'
  - ps: 'echo "IS PRE RELEASE ? $env:RELEASE_PRE"'
  - ps: 'echo "IS RELEASE DRAFT ? $env:RELEASE_DRAFT"'

deploy:
  - release: $(TRAKT_VERSION_NAME)
    description: $(TRAKT_VERSION_DESCRIPTION)
    provider: GitHub
    auth_token: $(GITHUB_TOKEN)
    artifact: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_BRANCH)-$(PLATFORM)
    draft: $(RELEASE_DRAFT)
    prerelease: $(RELEASE_PRE)
    on:
      should_deploy: yes
      appveyor_repo_tag: true

on_success:
  - ps : |
      if ($env:APPVEYOR_REPO_TAG -ne 'true' -and $env:APPVEYOR_REPO_BRANCH -eq 'testlua' -and $env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null -and $env:APPVEYOR_API_TOKEN -ne $null) {
          $env:UPDATE_LATEST = "true"
      } else {
          $env:UPDATE_LATEST = "false"
      }

  - if [%UPDATE_LATEST%]==[true] (
        pipenv install scikit-ci-addons &
        pipenv run ci_addons publish_github_release --prerelease-packages "dist\\%TRAKT_HELPER_BIN%" --prerelease-packages-clear-pattern "TraktForVLC_*_windows_%PLATFORM%.exe" --prerelease-packages-keep-pattern "%TRAKT_HELPER_BIN%" --prerelease-sha testlua "%APPVEYOR_REPO_NAME%"
    )
